AWSTemplateFormatVersion: '2010-09-09'
Description: |
  I can use this template to launch a Nested Stack 
  which eventually launches a S3 Bucket

Resources:
  s3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: 01_create_s3_bucket.yaml
      Parameters: 
        BucketName: test-1234567890-alamin-27-april
      TimeoutInMinutes: 2

Outputs:
  BucketName:
    Value: !GetAtt s3BucketStack.Outputs.BucketName
    Description: Name of the S3 Bucket
  BucketARN:
    Value: !GetAtt s3BucketStack.Outputs.BucketARN
    Description: ARN of the S3 Bucket
